# Generated by Django 4.0.6 on 2022-07-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='body',
            new_name='due',
        ),
        migrations.AddField(
            model_name='contest',
            name='link',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='title',
            field=models.TextField(),
        ),
    ]
