# Generated by Django 4.0.6 on 2022-07-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0002_rename_body_contest_due_contest_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('due', models.TextField()),
                ('link', models.URLField(default='', null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contest',
        ),
    ]
