# Generated by Django 4.0.6 on 2022-07-19 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0004_crawleddata_delete_contestdata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crawleddata',
            table=None,
        ),
    ]
