# Generated by Django 4.0.6 on 2022-07-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0006_alter_crawleddata_table'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='crawleddata',
            constraint=models.UniqueConstraint(fields=('title', 'due', 'link'), name='crawled_data'),
        ),
        migrations.AlterModelTable(
            name='crawleddata',
            table=None,
        ),
    ]
