# Generated by Django 4.0.6 on 2022-07-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0007_crawleddata_crawled_data_alter_crawleddata_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('due', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IdeaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('due', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SwData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('due', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WebData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('due', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='CrawledData',
        ),
        migrations.AddConstraint(
            model_name='webdata',
            constraint=models.UniqueConstraint(fields=('title', 'link'), name='web_contest'),
        ),
        migrations.AddConstraint(
            model_name='swdata',
            constraint=models.UniqueConstraint(fields=('title', 'link'), name='Sw_contest'),
        ),
        migrations.AddConstraint(
            model_name='ideadata',
            constraint=models.UniqueConstraint(fields=('title', 'link'), name='idea_contest'),
        ),
        migrations.AddConstraint(
            model_name='engineeringdata',
            constraint=models.UniqueConstraint(fields=('title', 'link'), name='engineering_contest'),
        ),
    ]
