# Generated by Django 4.0.6 on 2022-07-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0009_remove_engineeringdata_engineering_contest_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='swdata',
            name='Sw_contest',
        ),
        migrations.AddConstraint(
            model_name='swdata',
            constraint=models.UniqueConstraint(fields=('title', 'due', 'link'), name='sw_contest'),
        ),
    ]
