# Generated by Django 4.1 on 2022-08-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0011_spartanedu_spartanedu_spartan_notice'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='engineeringdata',
            name='engineering_contest',
        ),
        migrations.RemoveConstraint(
            model_name='ideadata',
            name='idea_contest',
        ),
        migrations.RemoveConstraint(
            model_name='swdata',
            name='sw_contest',
        ),
        migrations.RemoveConstraint(
            model_name='webdata',
            name='web_contest',
        ),
        migrations.AddConstraint(
            model_name='engineeringdata',
            constraint=models.UniqueConstraint(fields=('title', 'link'), name='engineering_contest'),
        ),
        migrations.AddConstraint(
            model_name='ideadata',
            constraint=models.UniqueConstraint(fields=('title', 'link'), name='idea_contest'),
        ),
        migrations.AddConstraint(
            model_name='swdata',
            constraint=models.UniqueConstraint(fields=('title', 'link'), name='sw_contest'),
        ),
        migrations.AddConstraint(
            model_name='webdata',
            constraint=models.UniqueConstraint(fields=('title', 'link'), name='web_contest'),
        ),
    ]
